pipelines:
  - name: demo_extn
    steps:
      - name: test_001
        type: sample
        syntaxVersion: 0.0.1
        configuration:
          downloadURL: https://github.com/devops-recipes/app-mono/archive/master.zip
          downloadPath: monoRepo
    steps:
      - name: test_002
        type: sample
        syntaxVersion: 0.0.2
        configuration:
          inputSteps:
            - test_001
          downloadURL: https://github.com/devops-recipes/app-mono/archive/master.zip
          downloadPath: monoRepo
          doUnzip: true
