#pipelines:
#  - name: demo_extn
#    steps:
#      - name: download
#        type: sample
#        configuration:
#          downloadURL: https://github.com/devops-recipes/app-mono/archive/master.zip

resources:
  - name: app_docker
    type: Image
    configuration:
      registry: art_master
      sourceRepository: docker-local
      imageName: pipe-master.jfrog.info:8082/docker-local/basicapi
      imageTag: latest
  - name: app_test_results
    type: PropertyBag
    configuration:
      passing: 0
      failing: 0
pipelines:
  - name: jenkins_demo_1
    configuration:
      nodePool: static-node-pool
    steps:
      - name: build_app
        type: Bash
        configuration:
          outputResources:
            - name: app_docker
        execution:
          onExecute:
            - write_output app_docker "imageTag={{gitBranch}}.${run_number}"
      - name: test_app
        type: Jenkins
        configuration:
          jenkinsJobName: basic-api-mb
          jenkinsBranchName: {{gitBranch}}
          inputResources:
            - name: app_docker
          buildParameters:
            imageName: ${res_app_docker_imageName}
            imageTag: ${res_app_docker_imageTag}
          integrations:
            - name: demo_jenkins
          outputResources:
            - name: app_test_results
      - name: deploy_app
        type: Bash
        configuration:
          inputResources:
            - name: app_test_results
        execution:
          onExecute:
            - printenv | grep res_app_test_results