template: true   # required for local templates
valuesFilePath: ./values.yml

resources:
  - name: pipeRepo
    type: GitRepo
    configuration:
      # SCM integration where the repository is located
      gitProvider: {{ .Values.myRepo.gitProvider }} # this will be replaced from values.yml
      # Repository path, including org name/repo name
      path: {{ .Values.myRepo.path }} # this will be replaced from values.yml
      branches:
        # Specifies which branches will trigger dependent steps
        include: master

  - name: docker_prod_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: bsArt
      buildName: dockerBuild
      buildNumber: 1

#  - name: app_docker
#    type: Image
#    configuration:
#      registry: demo_artifactory
#      sourceRepository: docker-local
#      imageName: dev.jfrog-pipelines.com:8082/docker-local/basicapi
#      imageTag: latest

pipelines:
#  - name: demo_extn
#    steps:
#      - name: down_001
#        type: DownloadTar
#        syntaxVersion: 0.0.1
#        configuration:
#          downloadURL: https://github.com/devops-recipes/app-mono/tarball/master
#          downloadPath: monoRepo
#
#      - name: down_002
#        type: DownloadTar
#        syntaxVersion: 0.0.2
#        configuration:
#          inputSteps:
#            - name: down_001
#          downloadURL: https://github.com/devops-recipes/app-mono/tarball/master
#          downloadPath: monoRepo
#          doUnzip: true

  - name: pipeSample
    configuration:
      environmentVariables:
        readOnly:
          pipeOne: 1
          pipeTwo: 2
    steps:
      - name: step1
        type: Bash
        configuration:
          nodePool: k8nodes
          environmentVariables:
            stepOne: 3
            stepTwo: 4
          inputResources:
            # Sets up step to be triggered when there are commit events to myFirstRepo
            - name: pipeRepo
        execution:
          onExecute:
            # Data from input resources is available as env variables in the step
            - echo $res_pipeRepo_commitSha
            # The next two commands add variables to run state, which is available to all downstream steps in this run
            # Run state documentation: https://www.jfrog.com/confluence/display/JFROG/Creating+Stateful+Pipelines#CreatingStatefulPipelines-RunState
            - add_run_variables current_runid=$run_id
            - add_run_variables commitSha=$res_pipeRepo_commitSha

      - name: step2
        type: Bash
        configuration:
          inputSteps:
            - name: step1
        execution:
          onExecute:
            # Demonstrates the availability of an env variable written to run state during step1
            - echo $current_runid
            - echo "commitSha is $commitSha"

  - name: winSample
    configuration:
      environmentVariables:
        readOnly:
          pipeOne: 1
    steps:
      - name: test
        type: PowerShell
        configuration:
          nodePool: w19-static
        execution:
          onExecute:
            - write-output  "executing step..."

  - name: docker_prod_pipeline
    steps:
      - name: docker_promote_build
        type: PromoteBuild
        configuration:
          failOnValidate: true
          copy: true
          targetRepository: docker-prod-local
          comment: "promoted via pipeline ${pipeline_name} in run number ${run_number}"
          integrations:
            - name: bsArt
          inputResources:
            - name: docker_dev_build_info
              trigger: false
          outputResources:
            - name: docker_prod_build_info