pipelines:
  - name: demo_extn
    steps:
      - name: download
        type: sample
        configuration:
          downloadURL: https://github.com/devops-recipes/app-mono/archive/master.zip
          downloadPath: monoRepo
